version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: control_gastos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: control_gastos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/src/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  pgdata:
